name: Setup Dependencies

description: 'Checkout code and install dependencies'
inputs:
  node_version:
    description: 'Node.js version to use'
    required: true
    default: '20'
  fontawesome_token:
    description: 'FontAwesome authentication token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
    - name: Create .npmrc
      run: |
        echo "@fortawesome:registry=https://npm.fontawesome.com/" > .npmrc
        echo "//npm.fontawesome.com/:_authToken=${{ inputs.fontawesome_token }}" >> .npmrc
    - name: Install dependencies
      id: npm-install
      run: npm ci
      shell: bash
      continue-on-error: false