name: Deploy Action

description: 'Deploy the project by running the deployment script.'

inputs:
  base_branch:
    description: 'Base branch to compare for affected deploys'
    required: true
  node_env:
    description: 'Node environment (e.g., development, production)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run affected deploys
      env:
        NODE_ENV: ${{ inputs.node_env }}
      run: npx nx affected --target=deploy --base=origin/${{ inputs.base_branch }} --head=HEAD
      shell: bash
