name: Main (Staging)

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check merge source branch
        if: "!startsWith(github.event.pull_request.head.ref, 'hotfix/') && !startsWith(github.event.pull_request.head.ref, 'release/')"
        run: |
          echo "Blocked: Pull requests to main must come from hotfix/* or release/* branches."
          exit 1