name: Main (Production)

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Setup Dependencies
        uses: ./.github/actions/setup
        with:
          fontawesome_token: ${{ secrets.FONTAWESOME_TOKEN }}

      - name: Run Semantic Release for versioning
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          NODE_ENV: 'production'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  merge-to-develop:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          token: ${{ steps.app-token.outputs.token }}

      - name: Merge main into develop
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git merge origin/main

      - name: Push changes to develop
        run: git push origin develop
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}