name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Create .npmrc
        run: |
          const fs = require('fs');
          fs.writeFileSync('.npmrc', "@fortawesome:registry=https://npm.fontawesome.com/\n");
          fs.appendFileSync('.npmrc', "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}\n");
        shell: node
      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
