name: Release

on:
  push:
    branches:
      - 'release/*'
  pull_request:
    branches:
      - 'release/*'
jobs:
  test:
    if: github.event.pull_request.head.ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Dependencies
        uses: ./.github/actions/setup
        with:
          fontawesome_token: ${{ secrets.FONTAWESOME_TOKEN }}

      - name: Get Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Lint
        uses: ./.github/actions/lint
      - name: Unit Test
        uses: ./.github/actions/test
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ steps.app-token.outputs.token }}
  chromatic:
    if: github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Dependencies
        uses: ./.github/actions/setup

      - name: Get Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ steps.app-token.outputs.token }}